// Catálogos del SAT para datos de facturación (CFDI). Los códigos y textos deben
// coincidir exactamente con lo que exige el proveedor de facturación al timbrar.

export const REGIMEN_FISCAL_OPTIONS: { code: string; label: string }[] = [
    { code: '601', label: 'General de Ley Personas Morales' },
    { code: '603', label: 'Personas Morales con Fines no Lucrativos' },
    { code: '605', label: 'Sueldos y Salarios e Ingresos Asimilados a Salarios' },
    { code: '606', label: 'Arrendamiento' },
    { code: '607', label: 'Régimen de Enajenación o Adquisición de Bienes' },
    { code: '608', label: 'Demás ingresos' },
    { code: '609', label: 'Consolidación' },
    { code: '610', label: 'Residentes en el Extranjero sin Establecimiento Permanente en México' },
    { code: '611', label: 'Ingresos por Dividendos (socios y accionistas)' },
    { code: '612', label: 'Personas Físicas con Actividades Empresariales y Profesionales' },
    { code: '614', label: 'Ingresos por intereses' },
    { code: '615', label: 'Régimen de los ingresos por obtención de premios' },
    { code: '616', label: 'Sin obligaciones fiscales' },
    { code: '620', label: 'Sociedades Cooperativas de Producción que optan por diferir sus ingresos' },
    { code: '621', label: 'Incorporación Fiscal' },
    { code: '622', label: 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras' },
    { code: '623', label: 'Opcional para Grupos de Sociedades' },
    { code: '624', label: 'Coordinados' },
    { code: '625', label: 'Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas' },
    { code: '626', label: 'Régimen Simplificado de Confianza' },
    { code: '628', label: 'Hidrocarburos' },
    { code: '629', label: 'De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales' },
    { code: '630', label: 'Enajenación de acciones en bolsa de valores' },
];

export const USO_CFDI_OPTIONS: { code: string; label: string }[] = [
    { code: 'G01', label: 'Adquisición de mercancías' },
    { code: 'D06', label: 'Aportaciones voluntarias al SAR.' },
    { code: 'I07', label: 'Comunicaciones satelitales' },
    { code: 'I06', label: 'Comunicaciones telefónicas' },
    { code: 'I01', label: 'Construcciones' },
    { code: 'I05', label: 'Dados, troqueles, moldes, matrices y herramental' },
    { code: 'D09', label: 'Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones.' },
    { code: 'G02', label: 'Devoluciones, descuentos o bonificaciones' },
    { code: 'D04', label: 'Donativos.' },
    { code: 'I04', label: 'Equipo de computo y accesorios' },
    { code: 'I03', label: 'Equipo de transporte' },
    { code: 'D08', label: 'Gastos de transportación escolar obligatoria.' },
    { code: 'G03', label: 'Gastos en general' },
    { code: 'D03', label: 'Gastos funerales.' },
    { code: 'D02', label: 'Gastos médicos por incapacidad o discapacidad' },
    { code: 'D01', label: 'Honorarios médicos, dentales y gastos hospitalarios.' },
    { code: 'D05', label: 'Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación).' },
    { code: 'I02', label: 'Mobiliario y equipo de oficina por inversiones' },
    { code: 'CN01', label: 'Nómina' },
    { code: 'I08', label: 'Otra maquinaria y equipo' },
    { code: 'CP01', label: 'Pagos' },
    { code: 'D10', label: 'Pagos por servicios educativos (colegiaturas)' },
    { code: 'P01', label: 'Por definir' },
    { code: 'D07', label: 'Primas por seguros de gastos médicos.' },
    { code: 'S01', label: 'Sin efectos fiscales' },
];
